# Generated by Django 3.0.4 on 2020-04-09 12:31

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeginnerRatingDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_datetime', models.DateTimeField(editable=False)),
                ('delta', models.IntegerField(default=0, verbose_name='Rating delta')),
                ('current_rating', models.IntegerField(editable=False, null=True, verbose_name='Current rating')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_datetime', models.DateTimeField(editable=False)),
                ('league', django_fsm.FSMField(default='beginner', editable=False, max_length=50)),
            ],
            options={
                'get_latest_by': 'period',
            },
        ),
    ]
