# Generated by Django 3.0.4 on 2020-06-21 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_auto_20200409_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beginner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_datetime', models.DateTimeField(editable=False)),
                ('delta', models.IntegerField(default=0, verbose_name='Rating delta')),
                ('value', models.IntegerField(editable=False, null=True, verbose_name='Current rating')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beginner_rating', to='rating.Rating')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='BeginnerRatingDetail',
        ),
    ]
