# Generated by Django 3.0.7 on 2020-06-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_auto_20200621_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beginner',
            name='delta',
            field=models.IntegerField(default=0, verbose_name='Изменение рейтинга'),
        ),
        migrations.AlterField(
            model_name='beginner',
            name='value',
            field=models.IntegerField(editable=False, null=True, verbose_name='Значение'),
        ),
    ]
