# Generated by Django 3.0.7 on 2020-06-29 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_auto_20200629_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='member',
            new_name='user',
        ),
    ]
