# Generated by Django 3.0.8 on 2020-08-02 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0005_auto_20200629_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beginner',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beginner_rating', to='rating.Rating'),
        ),
    ]
