# Generated by Django 3.0.4 on 2020-04-09 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('periods', '0001_initial'),
        ('moderation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationtomember',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='moderated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moderationtomember',
            name='moderation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation2member', to='moderation.Moderation'),
        ),
        migrations.AddField(
            model_name='moderation',
            name='members',
            field=models.ManyToManyField(through='moderation.ModerationToMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moderation',
            name='moderator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moderates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moderation',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moderators', to='periods.Period'),
        ),
    ]
