# Generated by Django 3.0.7 on 2020-06-29 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('periods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moderation', '0002_auto_20200409_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moderation',
            old_name='members',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='moderationtomember',
            old_name='member',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='moderationtomember',
            name='state',
            field=django_fsm.FSMField(default='to_accept', max_length=50, verbose_name='Статус модерации'),
        ),
    ]
