# Generated by Django 3.0.7 on 2020-06-29 23:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moderation', '0003_auto_20200629_2324'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModerationToMember',
            new_name='ModerationToUser',
        ),
    ]
