# Generated by Django 3.0.7 on 2020-07-05 17:50

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0004_auto_20200629_2337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'get_latest_by': 'period'},
        ),
        migrations.AddField(
            model_name='goal',
            name='description',
            field=models.CharField(default='Какая цель?', max_length=500, verbose_name='Описание цели'),
        ),
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('link', 'ссылка'), ('text', 'текст')], default='link', max_length=20, verbose_name='Тип пруфа')),
                ('description', models.CharField(default='Какой пруф?', max_length=500, verbose_name='Описание пруфа')),
                ('state', django_fsm.FSMField(default='new', max_length=50, protected=True, verbose_name='Статус пруфа')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moderation.Goal')),
            ],
        ),
    ]
