# Generated by Django 3.0.8 on 2020-07-25 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moderation', '0005_auto_20200705_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationtouser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moderated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
