# Generated by Django 3.0.8 on 2020-07-26 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0006_auto_20200725_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proof',
            name='type',
            field=models.CharField(choices=[('image', 'изображение'), ('link', 'ссылка'), ('text', 'текст')], max_length=20, verbose_name='Тип пруфа'),
        ),
    ]
