# Generated by Django 3.0.8 on 2020-07-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0007_auto_20200726_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='proof',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото/скрин'),
        ),
        migrations.AddField(
            model_name='proof',
            name='proof_link',
            field=models.URLField(blank=True, max_length=128, null=True, verbose_name='Ссылка'),
        ),
        migrations.AddField(
            model_name='proof',
            name='proof_text',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='proof',
            name='type',
            field=models.CharField(choices=[('image', 'фото/скрин'), ('link', 'ссылка'), ('text', 'текст')], max_length=20, verbose_name='Тип пруфа'),
        ),
    ]
