# Generated by Django 3.0.8 on 2020-07-27 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('periods', '0001_initial'),
        ('moderation', '0008_auto_20200726_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='periods.Period'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='state',
            field=django_fsm.FSMField(choices=[('new', 'новая'), ('accepted', 'согласована'), ('on_moderation', 'на проверке'), ('achieved', 'выполнена'), ('expired', 'просрочена'), ('failed', 'не выполнена')], default='new', max_length=50, protected=True, verbose_name='Статус цели'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moderationtouser',
            name='moderation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation2user', to='moderation.Moderation'),
        ),
        migrations.AlterField(
            model_name='moderationtouser',
            name='state',
            field=django_fsm.FSMField(choices=[('new', 'новая модерация'), ('goals_agreed', 'цели согласованы'), ('no_goals', 'нет целей'), ('period_failed', 'ПРОВАЛ'), ('success', 'УСПЕХ')], default='no_goals', max_length=50, protected=True, verbose_name='Статус модерации'),
        ),
        migrations.AlterField(
            model_name='moderationtouser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moderated_through', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proof',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='moderation.Goal'),
        ),
    ]
