# Generated by Django 3.0.8 on 2020-08-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0009_auto_20200727_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proof',
            name='proof_text',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Текст'),
        ),
    ]
