# Generated by Django 3.0.4 on 2020-04-09 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('periods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rating', to='periods.Period'),
        ),
        migrations.AddField(
            model_name='beginnerratingdetail',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beginner_rating', to='rating.Rating'),
        ),
    ]
